from . import help
from . import start
from . import quran_handler
from . import quran_handler2
from . import hadis_handler
from . import namoz_handler
from . import roza_handler
from . import duolar_handler
from . import darslar_handler
from . import dasturlar_handler
from . import kitoblar_handler
from . import multfilmlar_handler
from . import filmlar_handler
from . import foydali_bolim
from . import hayriya_handler
from . import qollash_handler
from . import admin_handler
from . import echo